### ISSUE TITLE
Codon adaptation index

### ISSUE THREAD

**Issue by AliYoussef96** [BioinfoHR/coRdon#2]
I was trying to calculate the CAI of a virus CDS named Escherichia virus T4. I used Escherichia coli CDS as a reference set ( both CDS were downloaded from NCBI database )

```R
cT.set <- codonTable(dna.set) #E.coli CDS
cT <- codonTable(dna) #T4 CDS
cai <- CAI(cT, subsets = list(cT.set), ribosomal = FALSE, 
      id_or_name2 = "11", alt.init = TRUE, stop.rm = TRUE, 
      filtering = "none")
```

It ran fine, but I think there is a problem in the algorithm implemented to estimate the CAI as I got some CAI values greater than 1, and as I know CAI ranges from 0 to 1.

**Comment by anamariaelek** [comment]
This is the definition of CAI that we implemented:

![image](https://user-images.githubusercontent.com/20280755/70331230-59fd4c00-183f-11ea-84af-b09473fac14e.png)


for codon j and the amino acid i, where X is the number of occurrences of this codons in the analysed sequence, F and Fmax are the frequency of this codon and of the most used codon for the same amino acid, respectively, and L is the analysed sequence length (in codons).

It follows from this definition that CAI will take values between 0 and 1 when the frequency (F) of most of the codons in the analysed sequence is less than the frequency of the most frequently used codon (Fmax) for the same amino acid. 

Given that you are using reference sequences from another organism, this could potentially cause CAI values to go above 1. I'll try to illustrate it with an example.

Let's say that codons for Gly in E.coli genes have the following frequencies:
GGU 0.5
GGC 0.4
GGG 0.05
GGA 0.05

In the T4 virus, let's say the frequencies are more uniform:
GGU 0.3
GGC 0.2
GGG 0.25
GGA 0.25

Now for both GGU and GGC, the ratio F/Fmax will be greater than 1. So if your E.coli sequences contain a lot of these codons (and they likely do, as these are the most frequent ones in E.coli), and other cases like this, the sum in the equation will eventually be positive, and consequently, CAI will be greater than 1.

**Comment by AliYoussef96** [comment]
Thank you for your explanation!! I got it.
