### ISSUE TITLE
For help about doing Visualisation of CU bias

### ISSUE THREAD

**Issue by YUZHAN2019** [BioinfoHR/coRdon#4]
Dear Contributor,
        Thanks very much for your helpful package. I am using it analyzing codon bias in yeast sequences. While I am doing the Visualisation of CU bias, I always get error using the reference genes (the first 81 genes). Could you provide me an example how to use reference genes to do the graph, or give me some suggestions?  I appreciate your help. My code and errors are following:

library(ggplot2)
genes <- getID(Scer_1)
refer <- getID(Scer_1[1:81,])
xlab <- "MILC distance from sample centroid"
ylab <- "MILC distance from gc genes"
Bplot(x = "Reference", y = "self",  reference = refer, annotations = genes, data = milc_3, size = 5, alpha = 0.5) + labs(x = xlab, y = ylab)
Error in .makedt(dt, annotations, ribosomal, reference) : 
  Reference must be a named list of length 1!

Yu
0106

**Comment by anamariaelek** [comment]
Hi Yu,

check out the package [vignette](https://www.bioconductor.org/packages/devel/bioc/vignettes/coRdon/inst/doc/coRdon.html#visualisation-of-cu-bias):

> To indicate any other gene(s), use reference argument. reference takes a list of length 1, containing either a logical vector in which TRUE corresponds (by position) to genes that are to be indicated on the plot, and FALSE to all the other genes, or a character vector of annotations for the genes to be indicated on the plot.


Assuming this is causing problems in your case, that should work if you do:

```
refer <- list(selected_genes = getID(Scer_1[1:81,]))
```

**Comment by YUZHAN2019** [comment]
It works, I appreciate your help. Yu
