### ISSUE TITLE
help

### ISSUE THREAD

**Issue by lfaino** [BioinfoHR/coRdon#5]
Dear @anamariaelek ,
I need some help. i`m very new to codon usage analysis and I need some advice.

I have a genome and I would like to check if specific chromosomes have a different codon usage compared to the rest of the genome.
To do so, I`m comparing all CDSs of the genome minus the genes of the chromosome that I choose to test with the CDSs of the chromosome under test. 

to do so I`m doing:

`dnaCore <- readSet(
  file="/home/lfaino/lfainoData/data2/F_verticill_others/Fv10027_core.fasta"
)
core <- codonTable(dnaCore)
dnaLS <- readSet(
  file="/home/lfaino/lfainoData/data2/F_verticill_others/Fv10027_disp.fasta"
)
LS <- codonTable(dnaLS)

intraBplot(core, LS, names = c("core", "LS"), 
           variable = "MILC")`

however, i do not know if it is corret or not.
can you please help?

cheers
Luigi

**Comment by anamariaelek** [comment]
Hi Luigi,

in priciple, yes - this should give you a visual comparison of codon usage in the two sets of genes.

However, I would maybe also consider using as a backround not all the genes on other chromosomes, but rather a subset that's matching e.g. the GC content and/or length of your foreground genes, as these can influence the values of codon usage metrics. But of course, in the end it depends on the sequence properties of the genome you are working with - this is just my guess and what I would do to try and make sure that whatever result you might see is not an artifact.

Hope it helps,

Anamaria
