### ISSUE TITLE
v.1.2.0

### ISSUE THREAD

**Issue by mmikedis** [BioinfoHR/coRdon#6]
Hi Anamaria,

I've used coRdon coRdon v.1.2.0 (published 2019-05-02) for an analysis that I'm in the process of publishing. 

In citing coRdon v.1.2.0 in my manuscript, I've realized that github url referenced in the v.1.2.0 description <git_url: https://git.bioconductor.org/packages/coRdon> only contains an earlier version of coRdon and I can't find v.1.2.0.

Is v.1.2.0 available on some other url that should be referenced for my manuscript?

Thank you,
Maria

**Comment by anamariaelek** [comment]
Hi Maria,

since there was never a publication for the package, in order to cite it, you can simply use the format as output by `citation('coRdon')` function in R, modifying the package version accordingly, of course:

```
> citation("coRdon")

To cite package ‘coRdon’ in publications use:

  Anamaria Elek, Maja Kuzman and Kristian Vlahovicek (2019). coRdon: Codon Usage Analysis and
  Prediction of Gene Expressivity. R package version 1.2.0. https://github.com/BioinfoHR/coRdon

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {coRdon: Codon Usage Analysis and Prediction of Gene Expressivity},
    author = {Anamaria Elek and Maja Kuzman and Kristian Vlahovicek},
    year = {2019},
    note = {R package version 1.2.0},
    url = {https://github.com/BioinfoHR/coRdon},
  }
```

Glad you found it useful!
