### ISSUE TITLE
Codon Usage readSet error

### ISSUE THREAD

**Issue by jrr1001** [BioinfoHR/coRdon#7]
Hello,
I'm very new at codon usage analysis. I just trying this package (coRdon), and the first issue I receive when trying to run the first command is "could not find function "readSet"":
> e_NC_045512.2 <- readSet(
+     file="ATGTACTCATTCGTTTCGGAAGAGACAGGTACGTTAATAGTTAATAGCGTACTTCTTTTTCTTGCTTTCG
+ TGGTATTCTTGCTAGTTACACTAGCCATCCTTACTGCGCTTCGATTGTGTGCGTACTGCTGCAATATTGT
+ TAACGTGAGTCTTGTAAAACCTTCTTTTTACGTTTACTCTCGTGTTAAAAATCTGAATTCTTCTAGAGTT
+ CCTGATCTTCTGGTCTAA")
Error in readSet(file = "ATGTACTCATTCGTTTCGGAAGAGACAGGTACGTTAATAGTTAATAGCGTACTTCTTTTTCTTGCTTTCG\nTGGTATTCTTGCTAGTTACACTAGCCATCCTTACTGCGCTTCGATTGTGTGCGTACTGCTGCAATATTGT\nTAACGTGAGTCTTGTAAAACCTTCTTTTTACGTTTACTCTCGTGTTAAAAATCTGAATTCTTCTAGAGTT\nCCTGATCTTCTGGTCTAA") : 
  could not find function "readSet"
> help(readSet)
No documentation for ‘readSet’ in specified packages and libraries:
you could try ‘??readSet’

What should I do?
Thanks in advance!

**Comment by anamariaelek** [comment]
Hi,

lookls like you didn't load the package:

```
library(coRdon)
```

Also, the function you are trying to use takes as an argument the path to the sequence file, not the sequence itself.

**Comment by jrr1001** [comment]
Thanks for your prompt response!
I tried to re-install the package:
> if (!requireNamespace("BiocManager", quietly=TRUE))
+     install.packages("BiocManager")
> BiocManager::install("coRdon")
Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.2 (2020-06-22)
Installing package(s) 'coRdon'
trying URL 'https://bioconductor.org/packages/3.11/bioc/bin/windows/contrib/4.0/coRdon_1.6.0.zip'
Content type 'application/zip' length 1423373 bytes (1.4 MB)
downloaded 1.4 MB

package ‘coRdon’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jdr_1\AppData\Local\Temp\RtmpWSIEHi\downloaded_packages

Then I tried to look for the coRdon Package:

> help(coRdon)
No documentation for ‘coRdon’ in specified packages and libraries:
you could try ‘??coRdon’

Then I received that issue.

Any idea of what is happening?
Thanks in advance!!!

**Comment by anamariaelek** [comment]
This is not a coRdon specific issue, this is how packages in R work - while you only need to install a package once, you still have to load it every time you start R. So just do `library(coRdon)` and everything should work.

**Comment by jrr1001** [comment]
Thank you!!!!!
I'm pretty new at this.
Thanks a lot!
